package com.elevenrax.dalmodel;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * A model representing a user's booking. 
 */
public class Booking {
	private static int seed = 1;
		
	private int bookingId;
	private String username;
	private long bookedon;
	private List<Flight> bookedFlights;
	
	/**
	 * @param bookingId - An autogenerated value for each booking, we would use @id and @GeneratedValue(strategy = GenerationType.IDENTITY) were there a Sql backend. 
	 * @param username - The user making the booking
	 * @param bookedFlights - A list of flight numbers that a user wishes to book
	 */
	public Booking(String username) {
		setBookingId();
		this.username = username;
		this.bookedFlights = new ArrayList<>();
		this.bookedon = Instant.now().getEpochSecond();
	}

	public int getBookingId() {
		return bookingId;
	}

	public void setBookingId() {
		this.bookingId = seed;
		seed++;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public List<Flight> getBookedFlights() {
		return bookedFlights;
	}

	public void addBookedFlights(Flight flight) {
		this.bookedFlights.add(flight);
	}
	
	public String getBookedon() {
		return getUserReadableDateTime(bookedon);
	}

	// Converts UnixTime into a user friendly time string.
	public String getUserReadableDateTime(long timestamp) {
		if (timestamp == -1) return "";
		Date dateTime = new Date((long)timestamp*1000);
		return dateTime.toString();
	}

}
